// Define and export the Record interface
export interface Record {
  screenRecording: string;
  date: string;
  intentLevel: number;
  purchaseValue: number;
  purchaseChange: number;
  entryPage: string;
  duration: string;
  pages: number;
  deviceType: string;
  videoUrl: string;
  pageClicks: number;
  deadClicks: number;
  browser: string;
}

// Define the records array and export it
const records: Record[] = [
  {
    screenRecording: "Oct 23, 15:53",
    date: "Today",
    intentLevel: 3,
    purchaseValue: 86.99,
    purchaseChange: 0,
    entryPage: "/home",
    duration: "05:20",
    pages: 3,
    deviceType: "desktop",
    videoUrl: new URL("@/assets/testvideo.mp4", import.meta.url).href,
    pageClicks: 15,
    deadClicks: 2,
    browser: "Chrome",
  },
  {
    screenRecording: "Oct 22, 13:40",
    date: "Today",
    intentLevel: 1,
    purchaseValue: 0.0,
    purchaseChange: -10,
    entryPage: "/products/bags/leather-bag",
    duration: "00:36",
    pages: 2,
    deviceType: "mobile",
    videoUrl: new URL("@/assets/testvideo2.mp4", import.meta.url).href,
    pageClicks: 5,
    deadClicks: 0,
    browser: "Safari",
  },
  {
    screenRecording: "Oct 21, 10:20",
    date: "Yesterday",
    intentLevel: 4,
    purchaseValue: 50.0,
    purchaseChange: 25,
    entryPage: "/product/shoes/running-shoes",
    duration: "20:03",
    pages: 4,
    deviceType: "tablet",
    videoUrl: new URL("@/assets/testvideo3.mp4", import.meta.url).href,
    pageClicks: 30,
    deadClicks: 5,
    browser: "Firefox",
  },
  {
    screenRecording: "Oct 20, 05:14",
    date: "2 days ago",
    intentLevel: 2,
    purchaseValue: 0.0,
    purchaseChange: 0,
    entryPage: "/product/shirts/casual-shirt",
    duration: "01:03",
    pages: 1,
    deviceType: "desktop",
    videoUrl: "/videos/recording4.mp4",
    pageClicks: 10,
    deadClicks: 1,
    browser: "Chrome",
  },
  {
    screenRecording: "Oct 19, 16:30",
    date: "3 days ago",
    intentLevel: 1,
    purchaseValue: 10.0,
    purchaseChange: 8,
    entryPage: "/collection/seasonal-deals",
    duration: "02:30",
    pages: 5,
    deviceType: "mobile",
    videoUrl: "/videos/recording5.mp4",
    pageClicks: 20,
    deadClicks: 3,
    browser: "Edge",
  },
  {
    screenRecording: "Oct 18, 12:00",
    date: "4 days ago",
    intentLevel: 2,
    purchaseValue: 20.0,
    purchaseChange: 5,
    entryPage: "/category/sports",
    duration: "03:45",
    pages: 2,
    deviceType: "desktop",
    videoUrl: "/videos/recording6.mp4",
    pageClicks: 12,
    deadClicks: 1,
    browser: "Chrome",
  },
  {
    screenRecording: "Oct 17, 09:15",
    date: "5 days ago",
    intentLevel: 4,
    purchaseValue: 15.0,
    purchaseChange: 10,
    entryPage: "/product/electronics/headphones",
    duration: "10:25",
    pages: 3,
    deviceType: "tablet",
    videoUrl: "/videos/recording7.mp4",
    pageClicks: 25,
    deadClicks: 4,
    browser: "Firefox",
  },
  {
    screenRecording: "Oct 16, 14:00",
    date: "6 days ago",
    intentLevel: 2,
    purchaseValue: 30.0,
    purchaseChange: -5,
    entryPage: "/home",
    duration: "07:12",
    pages: 4,
    deviceType: "mobile",
    videoUrl: "/videos/recording8.mp4",
    pageClicks: 18,
    deadClicks: 2,
    browser: "Safari",
  },
  {
    screenRecording: "Oct 15, 11:45",
    date: "7 days ago",
    intentLevel: 3,
    purchaseValue: 120.0,
    purchaseChange: 15,
    entryPage: "/product/accessories/wallet",
    duration: "12:34",
    pages: 6,
    deviceType: "desktop",
    videoUrl: "/videos/recording9.mp4",
    pageClicks: 40,
    deadClicks: 5,
    browser: "Edge",
  },
  {
    screenRecording: "Oct 14, 08:30",
    date: "8 days ago",
    intentLevel: 1,
    purchaseValue: 0.0,
    purchaseChange: -20,
    entryPage: "/products/sale",
    duration: "00:55",
    pages: 2,
    deviceType: "mobile",
    videoUrl: "/videos/recording10.mp4",
    pageClicks: 7,
    deadClicks: 1,
    browser: "Chrome",
  },
  {
    screenRecording: "Oct 13, 13:25",
    date: "9 days ago",
    intentLevel: 2,
    purchaseValue: 45.0,
    purchaseChange: 10,
    entryPage: "/product/books/novel",
    duration: "06:10",
    pages: 3,
    deviceType: "tablet",
    videoUrl: "/videos/recording11.mp4",
    pageClicks: 15,
    deadClicks: 2,
    browser: "Safari",
  },
  {
    screenRecording: "Oct 12, 17:00",
    date: "10 days ago",
    intentLevel: 4,
    purchaseValue: 200.0,
    purchaseChange: 50,
    entryPage: "/exclusive/offers",
    duration: "18:45",
    pages: 5,
    deviceType: "desktop",
    videoUrl: "/videos/recording12.mp4",
    pageClicks: 35,
    deadClicks: 3,
    browser: "Firefox",
  },
  {
    screenRecording: "Oct 11, 20:05",
    date: "11 days ago",
    intentLevel: 3,
    purchaseValue: 75.0,
    purchaseChange: 0,
    entryPage: "/product/home/furniture",
    duration: "15:00",
    pages: 4,
    deviceType: "desktop",
    videoUrl: "/videos/recording13.mp4",
    pageClicks: 28,
    deadClicks: 0,
    browser: "Edge",
  },
  {
    screenRecording: "Oct 10, 06:45",
    date: "12 days ago",
    intentLevel: 2,
    purchaseValue: 0.0,
    purchaseChange: -15,
    entryPage: "/search/results?q=shoes",
    duration: "02:10",
    pages: 1,
    deviceType: "mobile",
    videoUrl: "/videos/recording14.mp4",
    pageClicks: 5,
    deadClicks: 2,
    browser: "Safari",
  },
  {
    screenRecording: "Oct 09, 13:50",
    date: "13 days ago",
    intentLevel: 1,
    purchaseValue: 0.0,
    purchaseChange: 0,
    entryPage: "/home",
    duration: "00:45",
    pages: 1,
    deviceType: "desktop",
    videoUrl: "/videos/recording15.mp4",
    pageClicks: 6,
    deadClicks: 1,
    browser: "Chrome",
  },
];

export default records;
